### ISSUE TITLE
Auto generated docs

### ISSUE THREAD

**Issue by multimeric** [MauricePasternak/pathlib-js#1]
Hi, this looks like a great project. Any chance of setting up something like TsDoc + TypeDoc and publishing on github pages, so the docs are all in one place?

**Comment by MauricePasternak** [comment]
Better late than never! Thank you for this suggestion. It has been implemented and future versions will try to incorporate better examples to illustrate the particular behaviors that this library has (i.e. auto-resolving during instantiation of a Path).
