### ISSUE TITLE
Differences from Python

### ISSUE THREAD

**Issue by djmattyg007** [MauricePasternak/pathlib-js#2]
I've started trying to use this package in a new project I'm working on, and have run into a couple of behavioural differences from the python implementation. Is this meant to be a one-to-one mapping of python functionality?

A few examples:

- There is no `suffix` property. Instead there's a `ext` property, and it doesn't contain the leading `.`.
- Relative paths don't seem to be supported. Constructing a new Path object automatically canonicalises the underlying path string.

**Comment by MauricePasternak** [comment]
It is meant to be an approximation of the pathlib library from Python, but not a one-for-one. The general functionality for most use cases should be the same.

Regarding your first point: while there is no suffix property, the `ext` property should feature the leading `.` character, as it is derived from node's own `path.parse`, which includes the leading dot character.

Regarding the second point, yes, I'd even go so far as to say that is the most egregious difference: relative path characters are auto-resolved during instantiation. In an update to typeDoc standard, the class docstring will include examples of this behavior as a forewarning of the behavior.
